[build]
  command = "npm run build"
  publish = "out"
  functions = "out/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins.inputs]]
  target = "node16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200