import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.scss";
import pagestyles from "@/styles/home/Main.module.scss";
import {useDispatch, useSelector} from "react-redux";
import {useEffect, useRef} from "react";
import {closeNav, setNav} from "@/redux-actions/homeNavSlice";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import {
  Box,
  Button,
  Card,
  CardBody,
  Flex,
  FormControl,
  Input,
  InputGroup,
  InputLeftElement,
  Link,
  Text,
  Textarea,
} from "@chakra-ui/react";
import TopWidget from "@/components/pages/TopWidget";
import BottomWidget from "@/components/pages/BottomWidget";
import NotificationPopup from "@/components/home/NotificationPopup";
import {SiWhatsapp} from "react-icons/si";
import MainLayout from "../layout/Mainlayout";
import {RootState} from "@/redux-store/store";
import {IoMailOutline} from "react-icons/io5";

const inter = Inter({subsets: ["latin"]});

export default function Index() {
  const dispatch = useDispatch();
  const sideNavRef: any = useRef();
  const {adminAccounts} = useSelector((store: RootState) => store.HomeAppSlice);
  const adminAccount = adminAccounts[0];
  const handleClickOutside = (event: any) => {
    if (sideNavRef.current && !sideNavRef.current.contains(event.target)) {
      dispatch(closeNav());
    }
  };
  useEffect(() => {
    const navState = localStorage.getItem("home-nav");
    let navstate = navState ? JSON.parse(navState) : null;
    if (navstate) {
      dispatch(setNav(navstate));
    }
  }, []);

  useEffect(() => {
    document.addEventListener("click", handleClickOutside);

    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Contact | GLOBAL TYCOON FX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo2-transparent.png" />
      </Head>
      <MainLayout>
        <div>
          <main className={` ${pagestyles.body}`}>
            <div
              className={` ${pagestyles.contacts_top_head} ${pagestyles.top_head}`}
            >
              <Flex
                direction={"column"}
                gap={[7, 8, 9, 10, 12]}
                height={{base: "10rem", lg: "12rem", xl: "12rem"}}
                align={"center"}
                justify={"center"}
                textAlign={{base: "center", lg: "start", xl: "start"}}
                className={` ${pagestyles.about_top_head} ${pagestyles.top_head}`}
              >
                <Text fontSize={[32, 38, 44, 48, 52]}>OUR CONTACTS</Text>
              </Flex>
            </div>
          </main>
          <div
            className={`footer_line_through`}
            style={{zIndex: 1, position: "relative"}}
          />
          <Flex
            className={` ${pagestyles.body}`}
            style={{background: "rgb(14, 17, 19)"}}
          >
            <Flex direction={"column"} gap={1} align={"center"} w={"100%"}>
              <Text fontSize={[20, 24, 28, 32, 36]}>SEND MESSAGE</Text>
              <Text
                fontSize={[16, 17, 18, 19, 20]}
                color={"#bdbdbd"}
                textAlign={"center"}
              >
                Send us a message and we will reply to you within 24 hours!
              </Text>
            </Flex>
            <Flex justify={"center"} w={"100%"}>
              <Link
                color={"#bdbdbd"}
                target="_blank"
                href={`mailto:${adminAccount.email}?subject=GlobalTycoonFX%20HelpME`}
              >
                <Flex
                  justify={"center"}
                  bg={"#000"}
                  p={1}
                  px={4}
                  borderRadius={18}
                  align={"center"}
                  gap={2}
                >
                  <IoMailOutline fontSize={20} />
                  <Box>{adminAccount.email}</Box>
                </Flex>
              </Link>
            </Flex>
            <Flex justify={"center"} w={"100%"}>
              <Card
                background={"rgb(37, 44, 49)"}
                minW={{
                  base: "20rem",
                  sm: "24rem",
                  md: "28rem",
                  lg: "32rem",
                  xl: "40rem",
                }}
              >
                <Flex
                  direction={"column"}
                  gap={2}
                  p={{base: "1rem", lg: "2rem"}}
                >
                  <FormControl p={2} color={"#fff"}>
                    <Text
                      mb="8px"
                      fontSize={[12, 12, 14, 14, 16]}
                      color={"#fff"}
                    >
                      Email:{" "}
                    </Text>
                    <InputGroup>
                      <Input
                        type="tel"
                        className={`${styles.input}`}
                        fontSize={[12, 12, 14, 16, 18]}
                        required
                        placeholder="Email Address"
                      />
                    </InputGroup>
                  </FormControl>
                  <FormControl p={2} color={"#fff"}>
                    <Text
                      mb="8px"
                      fontSize={[12, 12, 14, 14, 16]}
                      color={"#fff"}
                    >
                      Messages:{" "}
                    </Text>
                    <Textarea
                      fontSize={[12, 12, 14, 16, 18]}
                      placeholder="What's the message"
                    />
                  </FormControl>
                  <FormControl>
                    <Button
                      fontSize={[12, 13, 14, 15, 16]}
                      type="submit"
                      w="100%"
                      _hover={{
                        background: "#64d2b1",
                      }}
                      color={"#fff"}
                      background="#55b598"
                    >
                      Send
                    </Button>
                  </FormControl>
                </Flex>
              </Card>
            </Flex>
          </Flex>
        </div>
      </MainLayout>
    </>
  );
}
